export const ProjectsData = [
    {
        "_id": "66dea220f9a701b265acd2a3",
        "projectName": "Giridhari Prospera",
        "projectLocation": "NBD - New Business District, Kismatpur, Hyderabad",
        "propertyType": "Ultra luxury triplex Villas",
        "projectdescription": "A luxurious villa project with top-notch amenities and spacious living.",
        "projectImages": [],
        "homearea": 4020,
        "rooms": 5,
        "baths": 6,
        "yearbuilt": 2024,
        "dimensions": "50x60 ft",
        "beds": 4,
        "price": 15000000,
        "status": "Available",
        
        "amenities": [
            "Clubhouse",
            "Swimming Pool",
            "Banquets",
            "Gym",
            "Children play area"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 1,
        "builderName": "Giridhari Builders",
        "projectBHK": [
            4,
            5
        ],
        "unitsApartments": "121 Units",
        "approvals": "P02400002730",
        "createdAt": "2024-09-09T07:22:08.805Z",
        "updatedAt": "2024-09-09T07:22:08.805Z",
        "__v": 0
    },
    {
        "_id": "66dea22df9a701b265acd2a6",
        "projectName": "Visions Arsha Apts",
        "projectLocation": "Tellapur Abutting On 100 ft Road",
        "propertyType": "Apartments",
        "projectdescription": "Modern apartments with excellent amenities and connectivity.",
        "projectImages": [],
        "homearea": 1390,
        "rooms": 3,
        "baths": 2,
        "yearbuilt": 2023,
        "dimensions": "40x50 ft",
        "beds": 2,
        "price": 8500000,
        "status": "Sold Out",
        "amenities": [
            "Club House",
            "Swimming Pool",
            "Gymnasium",
            "Indoor Games Room"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 2,
        "builderName": "Visions Builders",
        "projectBHK": [
            2,
            3,
            3.5
        ],
        "unitsApartments": "1561 Apartments",
        "approvals": "P01100005595",
        "createdAt": "2024-09-09T07:22:21.580Z",
        "updatedAt": "2024-09-09T07:22:21.580Z",
        "__v": 0
    },
    {
        "_id": "66dea287f9a701b265acd2ad",
        "projectName": "Moon Glade Apts of E infra & IRA - Joint Venture",
        "projectLocation": "Narsingi, Hyderabad",
        "propertyType": "Apartments",
        "projectdescription": "Spacious apartments with premium amenities.",
        "projectImages": [],
        "homearea": 1400,
        "rooms": 4,
        "baths": 3,
        "yearbuilt": 2022,
        "dimensions": "45x55 ft",
        "beds": 3,
        "price": 9500000,
        "status": "Available",
        
        "amenities": [
            "Gymnasium",
            "Tennis Court",
            "Kids Play Area",
            "Swimming Pool"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 3,
        "builderName": "E Infra",
        "projectBHK": [
            3,
            4
        ],
        "unitsApartments": "2400 Apartments",
        "approvals": "",
        "createdAt": "2024-09-09T07:23:51.786Z",
        "updatedAt": "2024-09-09T07:23:51.786Z",
        "__v": 0
    },
    {
        "_id": "66dea295f9a701b265acd2b0",
        "projectName": "Acasa Apts of Simcha Estates",
        "projectLocation": "Survey No.26/u, At Kokapet, West Hyderabad",
        "propertyType": "Apartments",
        "projectdescription": "Well-planned apartments with eco-friendly features.",
        "projectImages": [],
        "homearea": 3520,
        "rooms": 4,
        "baths": 3,
        "yearbuilt": 2024,
        "dimensions": "55x65 ft",
        "beds": 3,
        "price": 12000000,
        "status": "Available",
        
        "amenities": [
            "Swimming Pool",
            "Fire Sprinklers",
            "Landscaping & Tree",
            "24X7 Water Supply"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 4,
        "builderName": "Simcha Estates",
        "projectBHK": [
            3.5
        ],
        "unitsApartments": "102 Apartments",
        "approvals": "P02400006471",
        "createdAt": "2024-09-09T07:24:05.209Z",
        "updatedAt": "2024-09-09T07:24:05.209Z",
        "__v": 0
    },
    {
        "_id": "66dea2a0f9a701b265acd2b3",
        "projectName": "Lacasa Villa Venture at Adhibatla",
        "projectLocation": "La casa villas, behind TCS ADIBATLA, Hyderabad",
        "propertyType": "Villas",
        "projectdescription": "Spacious villas with luxury amenities and modern designs.",
        "projectImages": [],
        "homearea": 4054,
        "rooms": 5,
        "baths": 4,
        "yearbuilt": 2023,
        "dimensions": "60x70 ft",
        "beds": 4,
        "price": 18000000,
        "status": "Available",
        
        "amenities": [
            "24Hrs Water Supply",
            "Gym",
            "Cricket Court",
            "Landscaped Garden"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 5,
        "builderName": "Lacasa Builders",
        "projectBHK": [
            4
        ],
        "unitsApartments": "182 Units",
        "approvals": "P02400005578",
        "createdAt": "2024-09-09T07:24:16.565Z",
        "updatedAt": "2024-09-09T07:24:16.565Z",
        "__v": 0
    },
    {
        "_id": "66dea2a9f9a701b265acd2b6",
        "projectName": "Nivasa Apts at Tellapur",
        "projectLocation": "Kollure, Tellapur, West Hyderabad",
        "propertyType": "Apartments",
        "projectdescription": "Affordable apartments with modern amenities.",
        "projectImages": [],
        "homearea": 1375,
        "rooms": 3,
        "baths": 2,
        "yearbuilt": 2024,
        "dimensions": "35x45 ft",
        "beds": 2,
        "price": 7000000,
        "status": "Available",
        
        "amenities": [
            "Spa",
            "Swimming Pool",
            "Gymnasium",
            "Car Parking"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 6,
        "builderName": "Nivasa Builders",
        "projectBHK": [
            2,
            3
        ],
        "unitsApartments": "526",
        "approvals": "P01100007243",
        "createdAt": "2024-09-09T07:24:25.537Z",
        "updatedAt": "2024-09-09T07:24:25.537Z",
        "__v": 0
    },
    {
        "_id": "66dea2d3f9a701b265acd2b9",
        "projectName": "Skyven Kokapet main road-Prelaunch",
        "projectLocation": "Gandipet Hyderabad",
        "propertyType": "Apartments",
        "projectdescription": "Pre-launch of a new apartment complex.",
        "projectImages": [],
        "homearea": 0,
        "rooms": 0,
        "baths": 0,
        "yearbuilt": 0,
        "dimensions": "35x45 ft",
        "beds": 0,
        "price": 0,
        "status": "Prelaunch",
        
        "amenities": [],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 7,
        "builderName": "Skyven Builders",
        "projectBHK": [],
        "unitsApartments": "",
        "approvals": "",
        "createdAt": "2024-09-09T07:25:07.753Z",
        "updatedAt": "2024-09-09T07:25:07.753Z",
        "__v": 0
    },
    {
        "_id": "66dea2eef9a701b265acd2bc",
        "projectName": "Aparna Zenon",
        "projectLocation": "Puppalaguda, Hyderabad",
        "propertyType": "Apartments",
        "projectdescription": "High-end apartments with excellent facilities.",
        "projectImages": [],
        "homearea": 1326,
        "rooms": 3,
        "baths": 2,
        "yearbuilt": 2024,
        "dimensions": "42x52 ft",
        "beds": 2,
        "price": 9500000,
        "status": "Available",
        
        "amenities": [
            "Club House",
            "Power Back Up",
            "Lift",
            "Security",
            "Gymnasium"
        ],
        "locationiframe": "https://maps.google.com/embed?pb=...",
        "reviews": [],
        "builderid": 8,
        "builderName": "Aparna Builders",
        "projectBHK": [
            2,
            3
        ],
        "unitsApartments": "3664",
        "approvals": "P02400003722",
        "createdAt": "2024-09-09T07:25:34.595Z",
        "updatedAt": "2024-09-09T07:25:34.595Z",
        "__v": 0
    }
];